### ISSUE TITLE
SourceMapping is failing

### ISSUE THREAD

**Issue by hypery2k** [holisticon/angular-common#21]
karma tests are failing:

```
22 11 2016 09:13:43.764:ERROR [karma]: [TypeError: Cannot read property 'substr' of undefined]
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Projects/node_modules/source-map/lib/source-node.js:115:26)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (/Projects/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Projects/node_modules/source-map/lib/source-node.js:80:24)
    at SourceMapSource.node (/Projects/node_modules/webpack-sources/lib/SourceMapSource.js:42:20)
    at ReplaceSource.node (/Projects/node_modules/webpack-sources/lib/ReplaceSource.js:66:29)
    at CachedSource.node (/Projects/node_modules/webpack-sources/lib/CachedSource.js:12:23)
    at /Projects/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Projects/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Projects/node_modules/webpack-sources/lib/ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (/Projects/node_modules/webpack-sources/lib/ConcatSource.js:39:60)
    at /Projects/node_modules/webpack-sources/lib/ConcatSource.js:40:49
```

**Comment by hypery2k** [comment]
is also failing in webpack-dev-server
