### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' 

### ISSUE THREAD

**Issue by hypery2k** [holisticon/angular-common#32]
Getting following error with version 1.3.0 and Angular 4.0.3
```
[at-loader] Ok, 4.544 sec.
Hash: 0bfa8651041d55a0fa3f
Version: webpack 2.4.1
Time: 113851ms

ERROR in ./app/app.ts
Module build failed: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (10:0)
    at Parser.pp$5.raise (/backend/node_modules/babylon/lib/index.js:4452:13)
    at Parser.pp$1.parseStatement (/backend/node_modules/babylon/lib/index.js:1881:16)
    at Parser.parseStatement (/backend/node_modules/babylon/lib/index.js:5804:22)
    at Parser.pp$1.parseBlockBody (/backend/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseTopLevel (/backend/node_modules/babylon/lib/index.js:1778:8)
    at Parser.parse (/backend/node_modules/babylon/lib/index.js:1673:17)
    at Object.parse (/backend/node_modules/babylon/lib/index.js:7180:37)
    at Instrumenter.instrumentSync (/backend/node_modules/istanbul-lib-instrument/dist/instrumenter.js:121:31)
    at Instrumenter.instrument (/backend/node_modules/istanbul-lib-instrument/dist/instrumenter.js:176:32)
    at Object.module.exports (/backend/node_modules/istanbul-instrumenter-loader/index.js:25:25)
 @ /backend/src/test/frontend/app/app.spec.ts 1:0-53

ERROR in ./app/components/index.ts
```

**Comment by hypery2k** [comment]
fixed with 1.3.1
